definitions_version = 1

[[theme]]
name = "Amber"
repository = "https://github.com/di-effe/amber"
commit = "*"
version = "0.2.2"
leftwm_versions = ">0.2.10, <0.3.0"

[[theme]]
name = "arch-one-dark"
repository = "https://github.com/jamesbaker1901/leftwm-arch-one-dark/"
commit = "*"
version = "1.0.0"
leftwm_versions = "^0.3.0"

[[theme]]
name = "Ascent"
repository = "https://gitlab.com/mWalrus/ascent"
commit = "*"
version = "1.0.0"
leftwm_versions = ">0.2.7"

[[theme]]
name = "Bumblebee"
repository = "https://github.com/mfdorst/leftwm-bumblebee/"
commit = "*"
version = "0.0.1"
leftwm_versions = "^0.2.8, <0.3.0"

[[theme]]
name = "Catppuccin"
repository = "https://github.com/di-effe/catppuccin"
commit = "*"
version = "0.1.1"
leftwm_versions = ">0.2.10, <0.3.0"

[[theme]]
name = "Coffee"
repository = "https://github.com/lex148/leftwm-coffee/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"

[[theme]]
name = "Dementive"
repository = "https://github.com/dementive/leftwm-dementive"
commit = "*"
version = "0.1"
leftwm_versions = "^0.4.0"

[[theme]]
name = "Desire"
repository = "https://github.com/copypasteonly/Desire"
commit = "*"
version = "0.1"
leftwm_versions = "^0.4.0"

[[theme]]
name = "Double Bar"
repository = "https://github.com/PeterDauwe/doublebar/"
commit = "*"
version = "0.0.2"
leftwm_versions = "^0.3.0"

[[theme]]
name = "Dracula Rounded"
repository = "https://github.com/AethanFoot/leftwm-theme-dracula-rounded/"
commit = "*"
version = "0.0.3"
leftwm_versions = "^0.3.0"

[[theme]]
name = "Epitaph"
repository = "https://github.com/VentGrey/Epitaph"
commit = "*"
version = "0.0.2"
leftwm_versions = "*"

[[theme]]
name = "Flamingo"
repository = "https://github.com/necaris/leftwm-theme-flamingo"
commit = "*"
version = "0.0.1"
leftwm_versions = ">0.2.7, <0.3.0"

[[theme]]
name = "Forest"
repository = "https://github.com/lex148/forest/"
commit = "*"
version = "0.0.1"
leftwm_versions = "^0.3.0"

[[theme]]
name = "Garden"
repository = "https://github.com/taylor85345/leftwm-theme-garden"
commit = "*"
version = "0.0.4"
leftwm_versions = ">0.2.7"

[[theme]]
name = "minimal-solarized"
repository = "https://github.com/minda1975/minimal_solarized"
commit = "*"
version = "0.1.0"
leftwm_versions = "^0.3.0"

[[theme]]
name = "Molese"
repository = "https://github.com/m0lese/leftwm-config"
commit = "*"
version = "2.1.0"
leftwm_versions = ">0.2.10, <0.3.0"

[[theme]]
name = "Ocean-night"
repository = "https://github.com/TheRoniOne/ocean-night"
commit = "*"
version = "0.0.1"
leftwm_versions = "*"

[[theme]]
name = "Orange Forest"
repository = "https://github.com/PVautour/leftwm-theme-orange-forest/"
commit = "*"
version = "0.0.2"
leftwm_versions = "^0.3.0"

[[theme]]
name = "plan9"
repository = "https://github.com/seabassapologist/leftwm-theme-plan9"
commit = "*"
version = "0.1.0"
leftwm_versions = "^0.3.0"

[[theme]]
name = "Serika"
repository = "https://github.com/VuiMuich/leftwm-theme-serika.git"
commit = "*"
version = "0.0.1"
leftwm_versions = ">=0.3.0"

[[theme]]
name = "Soothe"
repository = "https://github.com/b4skyx/leftwm-soothe/"
commit = "*"
relative_directory = "theme/"
version = "0.0.1"
leftwm_versions = "<0.3.0"

[[theme]]
name = "sunflower"
repository = "https://github.com/mautamu/leftwm-sunflower/"
commit = "*"
version = "0.1.2"
leftwm_versions = "^0.2.11, <0.3.0"

[[theme]]
name = "Sunset"
repository = "https://github.com/Syudagye/leftwm-sunset"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"

[[theme]]
name = "TNG"
repository = "https://github.com/lex148/leftwm-tng/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"

[[theme]]
name = "Windows XP"
repository = "https://github.com/lex148/leftwm-windowsxp/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"

[[theme]]
name = "Zexanima"
repository = "https://github.com/calebgasser/zexanima-leftwm-theme/tree/develop"
commit = "*"
version = "0.0.1"
leftwm_versions = ">0.3.0"

[[theme]]
name = "Blood-Moon"
repository = "https://github.com/zawesomekid/Blood-Moon-leftwm-theme"
commit = "*"
version = "0.0.1"
leftwm_versions = ">0.3.0"

[[theme]]
name = "Late-Night"
repository = "https://github.com/JacoMalan1/LateNight"
commit = "*"
version = "0.0.2"
leftwm_versions = ">0.3.0"
