#possible keybindings
#https://github.com/leftwm/leftwm/blob/master/src/utils/xkeysym_lookup.rs

#Mod4 = Super key
modkey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
#tags = ["", "", "", "", "", "", "", "", ""]
#tags = ["www", "edit", "gimp", "inkscape", "meld", "video","vm", "files", "music"]

layouts = ["MainAndVertStack", "MainAndHorizontalStack", "MainAndDeck", "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "CenterMain", "CenterMainBalanced", "Monocle", "RightWiderLeftStack", "LeftWiderRightStack"]
#scratchpad = []
disable_current_tag_swap = true
focus_behaviour = "Sloppy"
#focus_behaviour = "ClickTo"
focus_new_windows = true

[[scratchpad]]
name = "MainTerminal" # This is the name which is referenced when calling (case-sensitive)
value = "xfce4-terminal" # The command to load the application if it isn't started

[[keybind]]
command = "Execute"
value = "killall conky"
modifier = ["modkey"]
key = "c"

[[keybind]]
command = "ToggleScratchPad"
value = "MainTerminal"
modifier = []
key = "F12"

[[keybind]]
command = "Execute"
value = "dmenu_run -i -nb '#191919' -nf '#fea63c' -sb '#fea63c' -sf '#191919' -fn 'NotoMonoRegular:bold:pixelsize=14'"
modifier = ["modkey","Shift"]
key = "d"

[[keybind]]
command = "Execute"
value = "arcolinux-logout"
modifier = ["modkey"]
key = "x"

[[keybind]]
command = "Execute"
value = "thunar"
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "Execute"
value = "leftwm-command ToggleFullScreen"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "Execute"
value = "urxvt"
modifier = ["modkey"]
key = "t"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["Control", "Alt"]
key = "t"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["Control", "Alt"]
key = "Return"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "space"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Shift"]
key = "space"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["Control","Alt"]
key = "Left"

[[keybind]]
command = "FocusNextTag"
modifier = ["Control", "Alt"]
key = "Right"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["Control","Alt"]
key = "Up"

[[keybind]]
command = "FocusNextTag"
modifier = ["Control", "Alt"]
key = "Down"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Tab"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey", "Shift"]
key = "Tab"

[[keybind]]
command = "FocusNextTag"
modifier = ["Alt"]
key = "Tab"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["Alt", "Shift"]
key = "Tab"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "ampersand"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "eacute"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "quotedbl"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "apostrophe"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "parenleft"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "section"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "egrave"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "exclam"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "ccedilla"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 1\" \"SendWorkspaceToTag 0 0\""
modifier = ["modkey", "Shift"]
key = "ampersand"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 2\" \"SendWorkspaceToTag 0 1\""
modifier = ["modkey", "Shift"]
key = "eacute"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 3\" \"SendWorkspaceToTag 0 2\""
modifier = ["modkey", "Shift"]
key = "quotedbl"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 4\" \"SendWorkspaceToTag 0 3\""
modifier = ["modkey", "Shift"]
key = "apostrophe"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 5\" \"SendWorkspaceToTag 0 4\""
modifier = ["modkey", "Shift"]
key = "parenleft"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 6\" \"SendWorkspaceToTag 0 5\""
modifier = ["modkey", "Shift"]
key = "section"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 7\" \"SendWorkspaceToTag 0 6\""
modifier = ["modkey", "Shift"]
key = "egrave"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 8\" \"SendWorkspaceToTag 0 7\""
modifier = ["modkey", "Shift"]
key = "exclam"

[[keybind]]
command = "Execute"
value = "leftwm-command \"SendWindowToTag 9\" \"SendWorkspaceToTag 0 8\""
modifier = ["modkey", "Shift"]
key = "ccedilla"
